### ISSUE TITLE
[BUG] Crash on beste.schule login

### ISSUE THREAD

**Issue by Konsl** [VPlanPlus-Project/VPlanPlus#469]
# What happened?/What is wrong?

Steps to reproduce:
- tap on "add vpp.ID"
- log into beste.schule in browser window
- app crashes

# Situation details (optional)

Browser: Chrome
Device: Samsung Galaxy A53
Class: JG11
Contact if you need additional info.

```
FATAL EXCEPTION: main
Process: es.jvbabi.vplanplus, PID: 30609
java.lang.NullPointerException
	at es.jvbabi.vplanplus.data.repository.ClassRepositoryImpl.getClassBySchoolIdAndClassName(ClassRepositoryImpl.kt:225)
	at es.jvbabi.vplanplus.data.repository.ClassRepositoryImpl$getClassBySchoolIdAndClassName$1.invokeSuspend(ClassRepositoryImpl.kt:17)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@453359e, Dispatchers.Main.immediate]
```

# How to fix (optional)

**Comment by Julius-Babies** [comment]
Your account seems to be linked to `11/1 - Tutorenkurs`, is this correct?

**Comment by Konsl** [comment]
Yes, that's correct

**Comment by Julius-Babies** [comment]
That explains it. The app tries to connect your vpp.ID with a class with the same name which comes from the stundenplan24.de data. Such a class doesn't exist there. Do you know, if your beste.schule account is linked to multiple so-called meta-groups? Maybe one of them is `JG11`. For now, I can manually fix your profile in the database.

Please try to re-login in VPlanPlus.

**Comment by Konsl** [comment]
From what I can tell, there is only one meta group called `11/1 - Tutorenkurs`, as you mentioned.
There also exist other groups (like `11CH2`) but those are not meta groups.

**Comment by Julius-Babies** [comment]
So changing the class ids manually in my database is a workaround. Please tell your classmates to send me an email (julvin.babies@gmail.com) with their beste.schule account name and Stundenplan24.de class name if they're experiencing similar issues.
